# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college_major_score',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.College'),
        ),
        migrations.AlterField(
            model_name='college_major_score',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Major'),
        ),
    ]
